<?php

/**
 * Implements hook_menu().
 */
function cu_libraries_search_menu() {
  // Search settings
  $items['admin/config/system/librarysearch'] = array(
    'title' => 'Library Search Settings',
    'description' => 'Configure library search settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_libraries_search_settings_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function cu_libraries_search_settings_form($form, &$form_state) {
  $search_settings = variable_get('cu_libraries_search_settings', '');
  $form = array();
  $form['cu_libraries_search_settings'] = array(
    '#type' => 'textarea',
    '#default_value' => variable_get('cu_libraries_search_settings', ''),
    '#title' => t('Search Options'),
    '#description' => t('Enter one value per row in the form: <em>searchkey|Search Name|Search URL</em>'),
    '#wysiwyg' => FALSE,
  );
  $form['cu_libraries_search_placeholder'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('cu_libraries_search_placeholder', 'Search'),
    '#title' => t('Search Placeholder'),
    '#description' => t('The placeholder text that appears in the search box.</em>'),
  );
  $form['hide_site_search'] = array(
    '#type' => 'radios',
    '#title' => t('Site Search'),
    '#options' => array(
      'show' => 'Show',
      'hide' => 'Hide',
    ),
    '#default_value' => variable_get('hide_site_search', 'show'),
    '#required' => TRUE,
  );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save Search Settings'));
  $form['#submit'][] = 'cu_libraries_search_settings_form_submit';
  return $form;
}

function cu_libraries_search_settings_form_submit($form, &$form_state) {
  $search_settings = $form_state['values']['cu_libraries_search_settings'];
  variable_set('cu_libraries_search_settings', $search_settings);
  $placeholder_settings = !empty($form_state['values']['cu_libraries_search_placeholder']) ?  $form_state['values']['cu_libraries_search_placeholder'] : 'Search';
  variable_set('cu_libraries_search_placeholder', $placeholder_settings);
  $site_search_settings = $form_state['values']['hide_site_search'];
  variable_set('hide_site_search', $site_search_settings);
  drupal_set_message(t('Search settings have been saved.'));
}

function cu_libraries_search_options() {
  $search_settings = variable_get('cu_libraries_search_settings', '');
  $search_options = explode("\n", $search_settings);
  $options = array();
  foreach ($search_options as $search_option) {
    $option = explode("|", $search_option);
    $options[$option[0]] = $option[1];
  }
  return $options;
}


function cu_libraries_search_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'cu_libraries_search') . '/css/cu-libraries-search.css');
  $site_search = variable_get('hide_site_search', 'show');
  if ($site_search == 'hide') {
    drupal_add_css('.search-toggle, .region-search-box {display:none !important;}', array('type' => 'inline'));
  }
}

/**
 * Implements hook_block_info().
 */
function cu_libraries_search_block_info() {
  $blocks['libraries_search_large'] = array(
    'info' => t('Large Libraries Search'),
  );
  $blocks['libraries_search_small'] = array(
    'info' => t('Small Libraries Search'),
  );
  return $blocks;
}

function cu_libraries_search_search_form($form, &$form_state) {
  $form = array();
  $placeholder = variable_get('cu_libraries_search_placeholder', 'Search');
  $form['libraries_search'] = array(
    '#type' => 'fieldset',
    '#title' => NULL,
    '#attributes' => array('class' => array('container-inline')),
  );
  $form['libraries_search']['search_string'] = array(
    '#type' => 'textfield',
    //'#default_value' => t('Search CU Libraries'),
    '#attributes' => array('placeholder' => $placeholder),
    '#title' => 'Search CU Libraries',
    '#title_display' => 'invisible',
  );
  $form['libraries_search']['search_type'] = array(
    '#type' => 'select',
    '#options' => cu_libraries_search_options(),
  );
  $form['libraries_search']['search_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#prefix' => '<div class="form-submit-wrapper">',
    '#suffix' => '</div>',
  );
  $form['#submit'][] = 'cu_libraries_search_search_form_submit';
  return $form;
}

function cu_libraries_search_search_form_submit($form, &$form_state) {
  $search_settings = variable_get('cu_libraries_search_settings', '');
  $search_options = explode("\n", $search_settings);
  $options = array();
  foreach ($search_options as $search_option) {
    $option = explode("|", $search_option);
    $options[$option[0]] = $option[2];
  }
  $query = urlencode($form_state['values']['search_string']);
  $destination = $form_state['values']['search_type'];
  // Build url
  if (strpos($options[$destination],'http') !== false) {
    $url = trim($options[$destination]) . trim($query);
    // Parse url for drupal_goto()
    $parts = parse_url($url);
    $site_url = $parts['scheme'] . '://' . $parts['host'] . $parts['path'];
    // Remove these from url array since we don't need them anymore
    unset($parts['scheme']);
    unset($parts['host']);
    unset($parts['path']);
    // Parse query string into array for drupal_goto()
    parse_str($parts['query'], $query_parts);
    $parts['query'] = $query_parts;
    drupal_goto($site_url, $parts);
  } else {
    global $base_url;
    $form_state['action'] = 'gsearch/';
    $search_query = urlencode($query . ' site:' . $base_url . '/' . $options[$destination]);
    $form_state['redirect'] = url($form_state['action'] . $search_query, array('absolute' => TRUE));
  }




}

function cu_libraries_search_block_view($delta = '') {
  switch ($delta) {
    case 'libraries_search_large':
      $search_background_image = variable_get('search_background_image', NULL);
      $block['subject'] = '';
      $search_form = drupal_get_form('cu_libraries_search_search_form');
      $block['content']['search_form'] = $search_form;
      $block['content']['#prefix'] = '<div class="cu-libaries-search-large" style="background-image:url(' . $search_background_image . ');">';
      $block['content']['#suffix'] = '</div>';

      // Get search content
      $search_content = variable_get('libraries_search_content_large', NULL);
      if (isset($search_content)) {
        $search_content = check_markup($search_content['value'], $search_content['format']);
        $block['subject'] = '';
        $block['content']['search_content']['#markup'] = $search_content;
        $block['content']['search_content']['#prefix'] = '<div class="libraries-search-content">';
        $block['content']['search_content']['#suffix'] = '</div>';
      }
      break;

    case 'libraries_search_small':
      // Get search form
      $search_form = drupal_get_form('cu_libraries_search_search_form');
      $block['content']['search_form'] = $search_form;

      // Get search content
      $search_content = variable_get('libraries_search_content_small', NULL);
      if (isset($search_content)) {
        $search_content = check_markup($search_content['value'], $search_content['format']);
        $block['subject'] = '';
        $block['content']['search_content']['#markup'] = $search_content;
        $block['content']['search_content']['#prefix'] = '<div class="libraries-search-content">';
        $block['content']['search_content']['#suffix'] = '</div>';
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function cu_libraries_search_block_configure($delta = '') {
  switch($delta) {
    case 'libraries_search_large':
      $search_background_image = variable_get('search_background_image', NULL);
      $search_content = variable_get('libraries_search_content_large', array(
        'value' => '',
        'format' => 'wysiwyg',
      ));
      $form['search_background_image'] = array(
        '#type' => 'textfield',
        '#title' => t('Search Background Image'),
        '#default_value' => $search_background_image,
        '#required' => FALSE,
      );
      $form['libraries_search_content'] = array(
        '#type' => 'text_format',
        '#title' => t('Libraries Search Content'),
        '#default_value' => $search_content['value'],
        '#format' => $search_content['format'],
        '#required' => FALSE,
      );
      break;
    case 'libraries_search_small':
      $search_content = variable_get('libraries_search_content_small', array(
        'value' => '',
        'format' => 'wysiwyg',
      ));
      $form['libraries_search_content'] = array(
        '#type' => 'text_format',
        '#title' => t('Libraries Search Content'),
        '#default_value' => $search_content['value'],
        '#format' => $search_content['format'],
        '#required' => FALSE,
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function cu_libraries_search_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'libraries_search_large':
      // Have Drupal save the string to the database.
      variable_set('search_background_image', $edit['search_background_image']);
      variable_set('libraries_search_content_large', $edit['libraries_search_content']);
      break;
    case 'libraries_search_small':
      // Have Drupal save the string to the database.
      variable_set('libraries_search_content_small', $edit['libraries_search_content']);
      break;
  }
  return;
}
